package conHashing

import (
	"crypto/md5"
	"encoding/hex"
	"math/big"
)
var hashRange = new(big.Int).Exp(big.NewInt(2), big.NewInt(128), nil)

type Ring struct {
    MaxID int
	NodesMap map[string][]int
}

func NewRing() *Ring {
    nodesMap := make(map[string][]int)
	return &Ring{MaxID:1, NodesMap: nodesMap}
}


/**
* Returns the position indicated by the hash
* Eg. return value = 0.8
* position = 0.8 * Total num of vNodes in ring
* 
* @param text The text to hash
* 
* @return the float generated by the hash
*/
func GetMD5Hash(text string) *big.Float {
	bi := big.NewInt(0)
	hasher := md5.New()
	hasher.Write([]byte(text))
	hexstr := hex.EncodeToString(hasher.Sum(nil))
	bi.SetString(hexstr, 16)
	hashFloat := new(big.Float).SetInt(bi)
	hashRangeFloat := new(big.Float).SetInt(hashRange)
	hash := new(big.Float).Quo(hashFloat,hashRangeFloat)
	return new(big.Float).Mul(hash, big.NewFloat(64))
}
