#Template
FROM golang:latest as main
WORKDIR /ShoppiDB
COPY ./go.mod ./
COPY ./go.sum ./
RUN go mod download
COPY ./src/*.go ./
COPY ./pkg ./pkg
RUN go build -o ./shoppidb

FROM redis:latest
RUN apt update
RUN apt install curl -y
WORKDIR /app
COPY --from=main /ShoppiDB/shoppidb ./
COPY ./wrapper_services.sh ./wrapper_services.sh 
CMD [ "./wrapper_services.sh"]
# CMD ["tail", "-f", "/dev/null"]
