version: "3.9"
services:
  node0: #DNS name 
      build:
        context: ./
        dockerfile: DockerFile_RedisNodeDev
      container_name: node0
      environment:
        - NODE_ID=0
        - RACE_DETECTOR=1
        - BUILD_ARGS=./src/main.go
        - SEEDNODES=${SEEDNODES}
      volumes:
        - .:/app
        - devnode0:/redis/volume
      networks:
        - db
  node1: #DNS name 
    build:
      context: ./
      dockerfile: DockerFile_RedisNodeDev
    container_name: node1
    environment:
      - NODE_ID=1
      - RACE_DETECTOR=1
      - BUILD_ARGS=./src/main.go
      - SEEDNODES=${SEEDNODES}
    volumes:
      - .:/app
      - devnode1:/redis/volume
    networks:
      - db
  node2: #DNS name 
    build:
      context: ./
      dockerfile: DockerFile_RedisNodeDev
    container_name: node2
    environment:
      - NODE_ID=2
      - RACE_DETECTOR=1
      - BUILD_ARGS=./src/main.go
      - SEEDNODES=${SEEDNODES}
    volumes:
      - .:/app
      - devnode2:/redis/volume
    networks:
      - db

volumes:
  devnode0:
  devnode1:
  devnode2:
networks:
  db:
    name: db_network
