version: "3.9"
services:
  shoppidb1: ## Easier dev env
    image: acim/go-reflex
    container_name: shoppidb1
    environment:
      - NODE_ID=1
      - RACE_DETECTOR=1
      - BUILD_ARGS=./src/main.go
    volumes:
      - .:/app
  redis_node:
    build:
      context: ./
      dockerfile: DockerFile_NodeInstance
    container_name: redis_node
    environment:
      - NODE_ID=1
  dev_redis_node:
    build:
      context: ./
      dockerfile: DockerFile_RedisNodeDev
    container_name: dev_redis_node
    environment:
      - NODE_ID=1
      - RACE_DETECTOR=1
      - BUILD_ARGS=./src/main.go
    volumes:
      - .:/app
      - devnode1:/redis/volume
    networks:
      - db

volumes:
  devnode1:
networks:
  db:
    name: db_network
