package main

import (
	"ShoppiDB/src/conHashing"
	"fmt"
	"log"
	"net"
	"os"
	"strings"
	"time"
)

func main() {
	id := os.Getenv("NODE_ID")
	seedNodes := os.Getenv("SEEDNODES")
	// ring := conHashing.NewRing(MAX_KEY)
	const maxNodes = 100
	node := conHashing.NewNode(id, maxNodes, strings.Split(seedNodes, ","))
	// fmt.Println("ring id:", node.Ring.MaxID)
	ln, err := net.Listen("tcp", ":8080")
	if err != nil {
		log.Fatal("server, Listen", err)
	}
	go listenMessage(ln)
	for {
		time.Sleep(time.Second * 10)
		sendMessage(node)
	}
	fmt.Println("End of Program")
}

func listenMessage(ln net.Listener) {
	fmt.Println("Start listening")
	// accept connection
	defer ln.Close()
	fmt.Println("Listening on :8080")
	fmt.Println("Waiting for client...")
	for {
		// get message, output
		connection, err := ln.Accept()
		if err != nil {
			fmt.Println("Error accepting: ", err.Error())
			os.Exit(1)
		}
		fmt.Println("client connected")
		go processClient(connection)
	}
}

func sendMessage(node conHashing.Node) {
	var id = node.ID
	hash := conHashing.GetMD5Hash(id)
	fmt.Println(hash)
	fmt.Println(id, "Sending message")
	// fmt.Println("Sending message")
	target, msg := getNode(id, node)
	time.Sleep(time.Millisecond * 1)
	con, err := net.Dial("tcp", target)

	if err != nil {
		fmt.Println("Dial accepting: ", err.Error())
		os.Exit(2)
	}
	defer con.Close() //Requires to catch the null error when fail to connect before writing

	checkErr(err)

	_, err = con.Write([]byte(msg))

	checkErr(err)
}

func getNode(id string, node conHashing.Node) (string, string) {
	switch id {
	default:
		fmt.Println("ERROR ID")
		return "null", "null"
	case "1":
		var msg = generateMessage(node)
		return "node2:8080", msg
	case "2":
		var msg = generateMessage(node)
		return "node1:8080", msg
	}
}

/**
* Returns an message generated by node
* @param node The node
*	seed node - return list of seed nodes, NodeRingPositions []
*
* @return an iterator over all the tuples stored in this DbFile.
*/
func generateMessage(node conHashing.Node) string {
	var isSeed = node.IsSeed
	fmt.Println(isSeed)
	switch isSeed {
	default:
		fmt.Println("ERROR ID")
		return "null"
	case true:
		// seedNodes := node.SeedNodes
		// fmt.Println("seedN:", seedNodes)
		return "From node 1" 
	case false:
		return "From node 2"
	}
	
}

func checkErr(err error) {

	if err != nil {
		fmt.Println("CONNECTION ERROR")
		fmt.Println(err)
	}
}

func processClient(connection net.Conn) {
	buffer := make([]byte, 1024)
	mLen, err := connection.Read(buffer)
	if err != nil {
		fmt.Println("Error reading:", err.Error())
	}
	fmt.Println("Received: ", string(buffer[:mLen]))
	connection.Close()
}
